project_id = "qfffsgiopzpwcijdkvcv"

[functions.update-brand-video]
verify_jwt = false

[functions.clear-analytics]
verify_jwt = false

[functions.update-app-setting]
verify_jwt = false

[functions.manage-pins]
verify_jwt = false

[functions.og-image]
verify_jwt = false
